### PR TITLE
Fixed flaky test

### LINKED ISSUE #188: [FlakyTest] org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints
```
REPRODUCE WITH: ./gradlew ':libs:h3:test' --tests "org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints" -Dtests.seed=D62B244E662CCF3F -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Pacific/Kiritimati -Druntime.java=17
org.opensearch.geospatial.h3.GeoToH3Tests > testRandomPoints FAILED

    java.lang.AssertionError

        at __randomizedtesting.SeedInfo.seed([D62B244E662CCF3F:D2ED166826AAC1D1]:0)
Suite: Test class org.opensearch.geospatial.h3.GeoToH3Tests
        at org.junit.Assert.fail(Assert.java:87)
  2> REPRODUCE WITH: ./gradlew ':libs:h3:test' --tests "org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints" -Dtests.seed=D62B244E662CCF3F -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Pacific/Kiritimati -Druntime.java=17
        at org.junit.Assert.assertTrue(Assert.java:42)
  2> java.lang.AssertionError
        at org.junit.Assert.assertTrue(Assert.java:53)
        at __randomizedtesting.SeedInfo.seed([D62B244E662CCF3F:D2ED166826AAC1D1]:0)
        at org.opensearch.geospatial.h3.GeoToH3Tests.testPoint(GeoToH3Tests.java:54)
        at org.junit.Assert.fail(Assert.java:87)
        at org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints(GeoToH3Tests.java:36)
        at org.junit.Assert.assertTrue(Assert.java:42)
  1> [2022-11-04T08:58:41,307][INFO ][o.o.g.h.GeoToH3Tests     ] [testRandomPoints] before test
        at org.junit.Assert.assertTrue(Assert.java:53)
  1> [2022-11-04T08:58:41,323][INFO ][o.o.g.h.GeoToH3Tests     ] [testRandomPoints] after test
        at org.opensearch.geospatial.h3.GeoToH3Tests.testPoint(GeoToH3Tests.java:54)
        at org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints(GeoToH3Tests.java:36)
  2> NOTE: leaving temporary files on disk at: /home/runner/work/geospatial/geospatial/libs/h3/build/testrun/test/temp/org.opensearch.geospatial.h3.GeoToH3Tests_D62B244E662CCF3F-001
  2> NOTE: test params are: codec=Lucene94, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=en-US, timezone=Pacific/Kiritimati
  2> NOTE: Linux 5.15.0-1022-azure amd64/Azul Systems, Inc. 17.0.5 (64-bit)/cpus=2,threads=1,free=4791[591](https://github.com/opensearch-project/geospatial/actions/runs/3388381977/jobs/5630520309#step:4:592)84,total=536870912
  2> NOTE: All tests run in this JVM: [CellBoundaryTests, CellCenterTests, GeoToH3Tests]
```

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
This fixes flaky reported test in testing random points.
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
```
3c22fb3bf9b7:geospatial balasvij$ ./gradlew ':libs:h3:test' --tests "org.opensearch.geospatial.h3.GeoToH3Tests.testRandomPoints" -Dtests.seed=D62B244E662CCF3F -Dtests.security.manager=true
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 14 (OpenJDK)
  JAVA_HOME             : /Users/balasvij/.sdkman/candidates/java/14.0.2-open
  Random Testing Seed   : D62B244E662CCF3F
  In FIPS 140 mode      : false
=======================================

> Task :libs:h3:test
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
```
 
### Issues Resolved
#188 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by naveentatikonda — APPROVED** [review]

File: libs/h3/src/test/java/org/opensearch/geospatial/h3/GeoToH3Tests.java [hunk 1]
```diff
@@ -33,28 +40,25 @@ public void testRandomPoints() {
...
-            }
-            assertTrue(minLat <= lat);
-            assertTrue(maxLat >= lat);
-            assertTrue(minLon <= lon);
-            assertTrue(maxLon >= lon);
+            GeoPolygon polygon = buildGeoPolygon(h3Address);
+            assertTrue(polygon.isWithin(point));
+        }
+    }
+    private GeoPolygon buildGeoPolygon(String h3Address) {
```
Comment (martin-gaievski) [inline libs/h3/src/test/java/org/opensearch/geospatial/h3/GeoToH3Tests.java:55]: nit: maybe add an empty line before method declaration

**Review by martin-gaievski — APPROVED** [review]
